services:

  app:
    container_name: company_catalog_app
    build:
      context: .
      dockerfile: src/backend.dockerfile
    env_file:
      - .env
#    ports:
#      - "8080:8080" # TODO убрать после добавления nginx
#      - "443:443"
    volumes:
      - ./src/infrastructure/db/alembic/versions:/app/src/infrastructure/db/alembic/versions:delegated
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head && python -m src.app"
    restart: on-failure

  db:
    container_name: company_catalog_db
    image: postgres:17
#    ports:
#      - "5432:5432" # TODO убрать после добавления nginx
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure

  nginx:
    image: nginx:1.26.3-alpine
    container_name: warehouse_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

volumes:
  postgres_data:
