services:

  app:
    container_name: company_catalog_app
    build:
      context: .
      dockerfile: src/backend.dockerfile
    ports:
      - "8080:8080" # TODO убрать после добавления nginx
      - "443:443"
    depends_on:
      - db

  db:
    container_name: company_catalog_db
    image: postgres:17
    ports:
      - "5432:5432" # TODO убрать после добавления nginx
    volumes:
      - company_catalog_db:/var/lib/postgres/data:rw
    env_file:
      - .env
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  company_catalog_db:
